stages:
- name: Testing
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: |-
        ls
        node -v
        npm -v
- name: Build Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: tinkeringaround/api
      registry: 127.0.0.1:34163
- name: Deploy Container
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 5
