stages:
- name: Build Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: tinkeringaround/api
- name: Deploy Container
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 5
