language: node_js
node_js: "node"

services:
  - docker

script:
  - npm run travis
  - docker login --username="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - docker build -t tinkeringaround/api:latest .
  - docker push tinkeringaround/api:latest
