language: node_js

services:
  - docker

before_deploy:
  - docker login --username="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - docker build -t tinkeringaround/api .

deploy:
  - docker push tinkeringaround/api:latest