language: node_js

services:
  - docker

script:
  - docker login --username="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - docker build -t tinkeringaround/api .
  - docker push tinkeringaround/api:latest