language: node_js

services:
  - docker

before_script:
  - docker login --username="${DOCKER_USERNAME}" --password-stdin

script:
  - docker build -t tinkeringaround/api .
  - docker push tinkeringaround/api:latest