language: node_js
node_js: "node"

services:
  - docker

before_install:
  - mkdir deployment
  - openssl enc -d -aes-192-cbc -in deployment/encrypted.enc -out deployment/cluster-kubeconfig.yaml -pass pass:${KEY}

script:
  - docker login --username="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - npm run test
  - npm run build
  - npm run cluster-delete
  - npm run cluster-create
