language: node_js

node_js:
  - "10"

services:
  - docker

before_install:
  - docker login --username="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - docker build -t tinkeringaround/api .
  - docker push tinkeringaround/api:latest