apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi
spec:
  selector:
    matchLabels:
      app: myapi
  replicas: 3
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
      - name: myapi
        image: tinkeringaround/api
        ports:
        - containerPort: 3000
---